<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>fr.icy</groupId>
        <artifactId>pom-icy</artifactId>
        <version>3.0.0-a.7</version>
    </parent>

    <groupId>fr.icy.extensions</groupId>
    <artifactId>imglib2</artifactId>
    <version>8.0.0-a.7</version>

    <name>ImgLib2 Icy</name>
    <description>ImgLib2 wrappers for Icy sequences.</description>
    <url>https://icy.bioimageanalysis.org/</url>
    <inceptionYear>2015</inceptionYear>

    <scm>
        <url>https://github.com/tinevez/imglib2-icy/</url>
        <tag>v${project.version}</tag>
    </scm>

    <issueManagement>
        <system>GitHub Issues</system>
        <url>https://github.com/tinevez/imglib2-icy/issues</url>
    </issueManagement>
    <ciManagement>
        <system>GitHub Actions</system>
        <url>https://github.com/tinevez/imglib2-icy/actions/</url>
    </ciManagement>

    <organization>
        <name>Institut Pasteur</name>
        <url>https://www.pasteur.fr/</url>
    </organization>

    <licenses>
        <license>
            <name>GNU LGPLv3</name>
            <url>https://www.gnu.org/licenses/lgpl-3.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>tinevez</id>
            <name>Jean-Yves Tinevez</name>
            <organization>Institut Pasteur</organization>
            <organizationUrl>https://pasteur.fr</organizationUrl>
            <url>https://icy.bioimageanalysis.org/author/tinevez/</url>
        </developer>
        <developer>
            <id>tmusset</id>
            <name>Thomas Musset</name>
            <organization>Institut Pasteur</organization>
            <organizationUrl>https://pasteur.fr</organizationUrl>
            <url>https://icy.bioimageanalysis.org/author/tmusset/</url>
        </developer>
    </developers>

    <contributors>
        <contributor>
            <name>Carlos Javier Garcia Lopez de Haro</name>
            <url>https://github.com/carlosuc3m</url>
        </contributor>
    </contributors>

    <mailingLists>
        <mailingList>
            <name>Icy</name>
            <post>icy.team@pasteur.fr</post>
        </mailingList>
    </mailingLists>

    <properties>
        <license.licenseName>GNU LGPLv3</license.licenseName>
        <license.copyrightOwners>Institut Pasteur</license.copyrightOwners>

        <imglib2-ui.version>2.0.1</imglib2-ui.version>
        <net.imglib2.imglib2-ui.version>${imglib2-ui.version}</net.imglib2.imglib2-ui.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>fr.icy.extensions</groupId>
            <artifactId>ezplug</artifactId>
            <version>${fr.icy.extensions.ezplug.version}</version>
        </dependency>

        <dependency>
            <groupId>net.imglib2</groupId>
            <artifactId>imglib2</artifactId>
            <version>${net.imglib2.imglib2.version}</version>
        </dependency>

        <dependency>
            <groupId>net.imglib2</groupId>
            <artifactId>imglib2-roi</artifactId>
            <version>${net.imglib2.imglib2-roi.version}</version>
        </dependency>
        <dependency>
            <groupId>net.imglib2</groupId>
            <artifactId>imglib2-realtransform</artifactId>
            <version>${net.imglib2.imglib2-realtransform.version}</version>
        </dependency>
        <dependency>
            <groupId>net.imglib2</groupId>
            <artifactId>imglib2-algorithm</artifactId>
            <version>${imglib2-algorithm.version}</version>
        </dependency>
        <dependency>
            <groupId>net.imglib2</groupId>
            <artifactId>imglib2-algorithm-fft</artifactId>
            <version>${imglib2-algorithm-fft.version}</version>
        </dependency>
        <dependency>
            <groupId>net.imglib2</groupId>
            <artifactId>imglib2-algorithm-gpl</artifactId>
            <version>${net.imglib2.imglib2-algorithm-gpl.version}</version>
        </dependency>
        <dependency>
            <groupId>net.imglib2</groupId>
            <artifactId>imglib2-ui</artifactId>
            <version>${net.imglib2.imglib2-ui.version}</version>
        </dependency>
        <dependency>
            <groupId>net.imglib2</groupId>
            <artifactId>imglib2-cache</artifactId>
            <version>${net.imglib2.imglib2-cache.version}</version>
        </dependency>
    </dependencies>
</project>